name: STAGE CD

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  deploy-to-prod:

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging machine
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_STAGE_TOKEN }}
          api-key: ${{ secrets.RENDER_KEY }}
